# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0003_auto_20161015_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='error',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='error message'),
        ),
        migrations.AddField(
            model_name='session',
            name='ovpn_pid',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='OpenVPN PID'),
        ),
        migrations.AddField(
            model_name='session',
            name='ovpn_ret',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='OpenVPN return code'),
        ),
    ]
