# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bott', '0004_auto_20161015_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ovpn_pid',
            field=models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='OpenVPN PID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ovpn_ret',
            field=models.PositiveSmallIntegerField(editable=False, null=True, verbose_name='OpenVPN return code'),
        ),
    ]
